/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Generated by gen/devinfo_extract.py -- do not edit by hand.
 *
 *   ./devinfo_extract.py --ogkm <open-gpu-kernel-modules at 535.129.03> \
 *       --version 535.129.03 --lang c > guest/linux/devinfo/v535_129_03.h
 *
 * Where driver 535.129.03 keeps each field of DRM_NVIDIA_GET_DEV_INFO.
 * See nvgpu_devinfo.h.
 */

static const struct nvgpu_devinfo_layout nvgpu_devinfo_v535_129_03 = {
	.size = 20,
	.at = {
		[NVGPU_DI_GPU_ID] = 0,
		[NVGPU_DI_MIG_DEVICE] = NVGPU_DI_ABSENT,
		[NVGPU_DI_PRIMARY_INDEX] = 4,
		[NVGPU_DI_SUPPORTS_ALLOC] = NVGPU_DI_ABSENT,
		[NVGPU_DI_GENERIC_PAGE_KIND] = 8,
		[NVGPU_DI_PAGE_KIND_GENERATION] = 12,
		[NVGPU_DI_SECTOR_LAYOUT] = 16,
		[NVGPU_DI_SUPPORTS_SYNC_FD] = NVGPU_DI_ABSENT,
		[NVGPU_DI_SUPPORTS_SEMSURF] = NVGPU_DI_ABSENT,
	},
};
