/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Generated by gen/devinfo_extract.py -- do not edit by hand.
 *
 *   ./devinfo_extract.py --ogkm <open-gpu-kernel-modules at 565.77.00> \
 *       --version 565.77.00 --lang c > guest/linux/devinfo/v565_77_00.h
 *
 * Where driver 565.77.00 keeps each field of DRM_NVIDIA_GET_DEV_INFO.
 * See nvgpu_devinfo.h.
 */

static const struct nvgpu_devinfo_layout nvgpu_devinfo_v565_77_00 = {
	.size = 32,
	.at = {
		[NVGPU_DI_GPU_ID] = 0,
		[NVGPU_DI_MIG_DEVICE] = NVGPU_DI_ABSENT,
		[NVGPU_DI_PRIMARY_INDEX] = 4,
		[NVGPU_DI_SUPPORTS_ALLOC] = 8,
		[NVGPU_DI_GENERIC_PAGE_KIND] = 12,
		[NVGPU_DI_PAGE_KIND_GENERATION] = 16,
		[NVGPU_DI_SECTOR_LAYOUT] = 20,
		[NVGPU_DI_SUPPORTS_SYNC_FD] = 24,
		[NVGPU_DI_SUPPORTS_SEMSURF] = 28,
	},
};
