/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Generated by gen/devinfo_extract.py -- do not edit by hand.
 *
 *   ./devinfo_extract.py --ogkm <open-gpu-kernel-modules at 615.71.09> \
 *       --version 615.71.09 --lang c > guest/linux/devinfo/v615_71_09.h
 *
 * Where driver 615.71.09 keeps each field of DRM_NVIDIA_GET_DEV_INFO.
 * See nvgpu_devinfo.h.
 */

static const struct nvgpu_devinfo_layout nvgpu_devinfo_v615_71_09 = {
	.size = 36,
	.at = {
		[NVGPU_DI_GPU_ID] = 0,
		[NVGPU_DI_MIG_DEVICE] = 4,
		[NVGPU_DI_PRIMARY_INDEX] = 8,
		[NVGPU_DI_SUPPORTS_ALLOC] = 12,
		[NVGPU_DI_GENERIC_PAGE_KIND] = 16,
		[NVGPU_DI_PAGE_KIND_GENERATION] = 20,
		[NVGPU_DI_SECTOR_LAYOUT] = 24,
		[NVGPU_DI_SUPPORTS_SYNC_FD] = 28,
		[NVGPU_DI_SUPPORTS_SEMSURF] = 32,
	},
};
