VK_DRIVER_FILES=/mnt/nvidia/share/vulkan/icd.d/nvidia_icd.json
__EGL_VENDOR_LIBRARY_DIRS=/mnt/nvidia/share/glvnd/egl_vendor.d
__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS=/mnt/nvidia/share/egl/egl_external_platform.d
GBM_BACKENDS_PATH=/mnt/nvidia/lib/gbm:/usr/lib/x86_64-linux-gnu/gbm:/usr/lib/gbm
GBM_BACKEND=nvidia-drm
AQ_DRM_DEVICES=/dev/dri/conduit-card
