/* SPDX-License-Identifier: GPL-2.0 */
/*
 * nvgpu_devinfo.h -- DRM_NVIDIA_GET_DEV_INFO in the release's own layout
 *
 * nvidia-drm answers GET_DEV_INFO with a struct of u32s that differs between
 * releases, and the ioctl number carries its size: 20 bytes in 535, 32 in
 * 565 through 570, 36 from 575 (a mig_device word second, which moves every
 * word after it). Answering a 32-byte caller with the 36-byte layout
 * overwrites four bytes of its stack and hands it every field one word off.
 *
 * So there is one record and one rule. The backend decodes the host's answer
 * once and sends the guest a record in a fixed order (enum nvgpu_di_field,
 * which is `abi::devinfo::Field`), whatever the host runs. This file encodes
 * it again for whatever size the caller's ioctl asks for, from the layouts in
 * devinfo/, generated by gen/devinfo_extract.py from each release's own
 * header. Nothing in the driver names a word by number.
 *
 * A size names one layout (a test in the backend's `abi` crate holds the
 * releases to that), which is how the caller's release is told from its
 * ioctl number alone.
 */

#ifndef NVGPU_DEVINFO_H
#define NVGPU_DEVINFO_H

#ifdef __KERNEL__
#include <linux/kernel.h>
#include <linux/string.h>
#include <linux/types.h>
#else
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
typedef uint8_t u8;
typedef uint32_t u32;
#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
#endif

/* The words of the wire record, in order. Add to the end only. */
enum nvgpu_di_field {
	NVGPU_DI_GPU_ID,
	NVGPU_DI_MIG_DEVICE,
	NVGPU_DI_PRIMARY_INDEX,
	NVGPU_DI_SUPPORTS_ALLOC,
	NVGPU_DI_GENERIC_PAGE_KIND,
	NVGPU_DI_PAGE_KIND_GENERATION,
	NVGPU_DI_SECTOR_LAYOUT,
	NVGPU_DI_SUPPORTS_SYNC_FD,
	NVGPU_DI_SUPPORTS_SEMSURF,
	NVGPU_DI_FIELDS,
};

/* An offset a release does not have. */
#define NVGPU_DI_ABSENT 0xffffffffu

/* The wire record is NVGPU_DI_FIELDS little-endian words. */
#define NVGPU_DI_WIRE_BYTES (4 * NVGPU_DI_FIELDS)

/* The decoded record: one value per field. */
struct nvgpu_devinfo {
	u32 v[NVGPU_DI_FIELDS];
};

struct nvgpu_devinfo_layout {
	u32 size; /* sizeof(struct drm_nvidia_get_dev_info_params) */
	u32 at[NVGPU_DI_FIELDS]; /* byte offset of each field, or ABSENT */
};

/* The per-release layouts, generated by gen/devinfo_extract.py --lang c. */
#include "devinfo/v535_129_03.h"
#include "devinfo/v565_77_00.h"
#include "devinfo/v580_178_04.h"
#include "devinfo/v595_104_02.h"
#include "devinfo/v595_71_05.h"
#include "devinfo/v610_57_04.h"
#include "devinfo/v615_71_09.h"

/* Every release's; a size names one layout, so the first of a size stands for
 * all of them (a test in the backend's `abi` crate holds the releases to it). */
static const struct nvgpu_devinfo_layout *const nvgpu_devinfo_layouts[] = {
	&nvgpu_devinfo_v535_129_03, &nvgpu_devinfo_v565_77_00,
	&nvgpu_devinfo_v580_178_04, &nvgpu_devinfo_v595_104_02,
	&nvgpu_devinfo_v595_71_05,  &nvgpu_devinfo_v610_57_04,
	&nvgpu_devinfo_v615_71_09,
};

/* The layout whose struct is exactly `size` bytes, or NULL. */
static inline const struct nvgpu_devinfo_layout *
nvgpu_devinfo_layout_for_size(u32 size)
{
	size_t i;

	for (i = 0; i < ARRAY_SIZE(nvgpu_devinfo_layouts); i++)
		if (nvgpu_devinfo_layouts[i]->size == size)
			return nvgpu_devinfo_layouts[i];
	return NULL;
}

/*
 * Write `d` as `l`'s struct to out[0 .. out_len): the fields the layout has,
 * and nothing else, and never a byte past out_len. Returns the bytes the
 * layout covers. The caller has chosen `l` by its own size, so out_len is
 * l->size in every call that matters; the bound is for the one that is not.
 */
static inline u32 nvgpu_devinfo_encode(const struct nvgpu_devinfo_layout *l,
				       const struct nvgpu_devinfo *d, u8 *out,
				       u32 out_len)
{
	int f;

	for (f = 0; f < NVGPU_DI_FIELDS; f++) {
		u32 at = l->at[f], v = d->v[f];

		if (at == NVGPU_DI_ABSENT || at > out_len || out_len - at < 4)
			continue;
		/* Little-endian, as the guest and the wire both are. */
		out[at + 0] = v;
		out[at + 1] = v >> 8;
		out[at + 2] = v >> 16;
		out[at + 3] = v >> 24;
	}
	return l->size;
}

#endif /* NVGPU_DEVINFO_H */
