/* SPDX-License-Identifier: GPL-2.0 */
/*
 * What size an NVIDIA escape ioctl may have, and what an NV_ESC_RM_ALLOC block
 * of each size looks like.
 *
 * One rule, owned by the host release. NVIDIA's kernel module compares the
 * size in the ioctl number against sizeof of each struct it understands
 * (rm_ioctl, escape.c) and answers anything else NV_ERR_INVALID_ARGUMENT. The
 * sizes are the release's -- NVIDIA's userspace is the host's, not the
 * guest's, so a literal here is one release's answer -- and they reach this
 * module from the backend in GET_SYS_FILES, generated by gen/nvabi_gen.py
 * from the same table the backend checks every call against
 * (abi::versions, IoctlEntry). This header only applies that list.
 *
 * Plain C, no libc: it builds in the module and in test/escape_test.c.
 */
#ifndef NVGPU_ESCAPE_H
#define NVGPU_ESCAPE_H

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
typedef uint32_t u32;
typedef uint8_t u8;
#endif

/* "NVES": opens the section of GET_SYS_FILES that carries the table. */
#define NVGPU_ESCAPE_SIZE_MAGIC 0x4e564553u
/* A record's size for an escape RM takes at any length. */
#define NVGPU_ESCAPE_SIZE_ANY 0xffffffffu
#define NVGPU_MAX_ESCAPE_SIZES 128

/* One accepted size of one escape (the low byte of the ioctl number). */
struct nvgpu_escape_size {
	u32 escape;
	u32 size;
};

/*
 * Whether the host release takes `size` bytes for `escape`.
 *
 * An escape the table does not list is not this function's to refuse: the
 * backend answers an escape outside the release's profile, and a module
 * talking to a backend that sent no table (n == 0) has no list to apply.
 */
static inline bool nvgpu_escape_size_ok(const struct nvgpu_escape_size *t,
					int n, u32 escape, u32 size)
{
	bool listed = false;
	int i;

	for (i = 0; i < n; i++) {
		if (t[i].escape != escape)
			continue;
		if (t[i].size == NVGPU_ESCAPE_SIZE_ANY || t[i].size == size)
			return true;
		listed = true;
	}
	return !listed;
}

/*
 * NV_ESC_RM_ALLOC takes two block sizes, in every release, and the fields
 * past the first five sit differently in each:
 *
 *   NVOS21_PARAMETERS (32)         NVOS64_PARAMETERS (48)
 *    0 hRoot                        0 hRoot
 *    4 hObjectParent                4 hObjectParent
 *    8 hObjectNew                   8 hObjectNew
 *   12 hClass                      12 hClass
 *   16 pAllocParms (8)             16 pAllocParms (8)
 *   24 paramsSize                  24 pRightsRequested (8)
 *   28 status                      32 paramsSize
 *                                  36 flags
 *                                  40 status
 *                                  44 (padding to 8-byte alignment)
 *
 * paramsSize is the caller's word for how long pAllocParms is, and is usually
 * zero: RM then takes the length from its own table for hClass.
 */
#define NVOS21_PARAMETERS_SIZE 32
#define NVOS64_PARAMETERS_SIZE 48

struct nvgpu_alloc_layout {
	u32 size;
	u32 params_size_at;
	u32 status_at;
};

/* The layout of an RM_ALLOC block this long, or NULL if RM takes none. */
static inline const struct nvgpu_alloc_layout *nvgpu_alloc_layout(u32 size)
{
	static const struct nvgpu_alloc_layout nvos21 = {
		NVOS21_PARAMETERS_SIZE, 24, 28 };
	static const struct nvgpu_alloc_layout nvos64 = {
		NVOS64_PARAMETERS_SIZE, 32, 40 };

	if (size == NVOS21_PARAMETERS_SIZE)
		return &nvos21;
	if (size == NVOS64_PARAMETERS_SIZE)
		return &nvos64;
	return NULL;
}

/* The little-endian word a block holds at `at`. */
static inline u32 nvgpu_le32_at(const void *block, u32 at)
{
	const u8 *b = (const u8 *)block + at;

	return (u32)b[0] | (u32)b[1] << 8 | (u32)b[2] << 16 | (u32)b[3] << 24;
}

#endif /* NVGPU_ESCAPE_H */
