/* SPDX-License-Identifier: GPL-2.0 */
/*
 * nvgpu_rmctrl.h — pointers inside an RM control's parameters
 *
 * A few RM controls hold an NvP64 in their parameter block, and RM copies
 * through it from the caller's address space. Through this device the caller
 * is the backend, so the guest's address must never get there: the backend
 * supplies the buffer and sizes it from the count field in these same
 * parameters.
 *
 * This half's job is to carry the bytes. For each pointer the table
 * describes, the driver sends what it addresses as a segment of the deep
 * block, and copies what comes back to where the caller's own pointer points.
 * The backend reads the same table, generated from the same probe over
 * NVIDIA's open-gpu-kernel-modules, so neither half has a layout the other
 * does not.
 *
 * A control not in the table is one RM does no embedded copy for, and is
 * forwarded as before. A control in it with `refuse` set is one the generator
 * could not describe; the backend answers it NV_ERR_NOT_SUPPORTED, and this
 * half sends no segments for it.
 */

#ifndef NVGPU_RMCTRL_H
#define NVGPU_RMCTRL_H

#include <linux/kernel.h>
#include <linux/types.h>

#include "nvgpu_version.h"

/* How a pointer's element count is found. */
enum nvgpu_rmctrl_count {
	NVGPU_RMCTRL_FIXED,   /* a constant from RM's own call site */
	NVGPU_RMCTRL_FIELD,   /* read from a field of the parameter block */
	NVGPU_RMCTRL_SQUARED, /* read from a field and squared (P2P caps) */
};

struct nvgpu_rmctrl_ptr {
	u32 ptr_offset;  /* where the NvP64 sits in the parameter block */
	u8 count_kind;   /* enum nvgpu_rmctrl_count */
	u32 count_offset;
	u8 count_width; /* 1, 2, 4 or 8 */
	u32 fixed;      /* the count, when it is a constant */
	u32 elem_size;
	bool copy_in;  /* RM reads the buffer before the control runs */
	bool copy_out; /* RM writes it afterwards */
};

struct nvgpu_rmctrl_entry {
	u32 cmd;
	u32 params_size;
	bool refuse;
	u16 ptr_first; /* index into the release's pointer array */
	u8 ptr_count;
};

/* The per-release tables, generated by gen/rmctrl_extract.py --lang c. */
#include "rmctrl/v535_129_03.h"
#include "rmctrl/v565_77_00.h"
#include "rmctrl/v580_178_04.h"
#include "rmctrl/v595_104_02.h"
#include "rmctrl/v595_71_05.h"
#include "rmctrl/v610_57_04.h"
#include "rmctrl/v615_71_09.h"

struct nvgpu_rmctrl_table {
	u32 major, minor, patch;
	const struct nvgpu_rmctrl_entry *entries;
	u32 n_entries;
	const struct nvgpu_rmctrl_ptr *ptrs;
	u32 n_ptrs;
};

#define NVGPU_RMCTRL_TABLE(maj, min, pat, id)                                  \
	{                                                                      \
		maj, min, pat, nvgpu_rmctrl_entries_##id,                      \
			ARRAY_SIZE(nvgpu_rmctrl_entries_##id),                 \
			nvgpu_rmctrl_ptrs_##id,                                \
			ARRAY_SIZE(nvgpu_rmctrl_ptrs_##id)                     \
	}

/* Ascending, as the backend's profiles are. */
static const struct nvgpu_rmctrl_table nvgpu_rmctrl_tables[] = {
	NVGPU_RMCTRL_TABLE(535, 129, 3, v535_129_03),
	NVGPU_RMCTRL_TABLE(565, 77, 0, v565_77_00),
	NVGPU_RMCTRL_TABLE(580, 178, 4, v580_178_04),
	NVGPU_RMCTRL_TABLE(595, 71, 5, v595_71_05),
	NVGPU_RMCTRL_TABLE(595, 104, 2, v595_104_02),
	NVGPU_RMCTRL_TABLE(610, 57, 4, v610_57_04),
	NVGPU_RMCTRL_TABLE(615, 71, 9, v615_71_09),
};

/* The most bytes one pointer may address, and one call may ask for. The same
 * numbers the backend uses: a call over them is refused there, so gathering
 * more here would only be work thrown away.
 */
#define NVGPU_RMCTRL_MAX_BYTES (1u << 20)
#define NVGPU_RMCTRL_MAX_TOTAL (2u * NVGPU_RMCTRL_MAX_BYTES)
/* As protocol::segments::MAX_SEGMENTS. */
#define NVGPU_RMCTRL_MAX_SEGMENTS 8

/*
 * nvgpu_rmctrl_table_for — the table for a host driver release.
 *
 * Its own, or the nearest older one, as the backend does. NULL when the
 * release is older than every table, or the version string is not one.
 * Nothing is guessed from a missing table: the driver sends no segments, and
 * the backend, which requires a segment for every pointer RM reads, refuses
 * the control. A control whose pointers are all null needs no segment and is
 * served either way, which is right -- there is nothing to copy.
 */
static inline const struct nvgpu_rmctrl_table *
nvgpu_rmctrl_table_for(const char *version)
{
	const struct nvgpu_rmctrl_table *best = NULL;
	u32 maj, min, pat;
	int i;

	if (!nvgpu_parse_version(version, &maj, &min, &pat))
		return NULL;

	for (i = 0; i < (int)ARRAY_SIZE(nvgpu_rmctrl_tables); i++) {
		const struct nvgpu_rmctrl_table *t = &nvgpu_rmctrl_tables[i];

		if (t->major > maj || (t->major == maj && t->minor > min) ||
		    (t->major == maj && t->minor == min && t->patch > pat))
			break;
		best = t;
	}
	return best;
}

/* The entry for one command, or NULL. The tables are sorted by command. */
static inline const struct nvgpu_rmctrl_entry *
nvgpu_rmctrl_find(const struct nvgpu_rmctrl_table *t, u32 cmd)
{
	int lo = 0, hi;

	if (!t)
		return NULL;
	hi = (int)t->n_entries - 1;
	while (lo <= hi) {
		int mid = lo + (hi - lo) / 2;

		if (t->entries[mid].cmd == cmd)
			return &t->entries[mid];
		if (t->entries[mid].cmd < cmd)
			lo = mid + 1;
		else
			hi = mid - 1;
	}
	return NULL;
}

/*
 * nvgpu_rmctrl_len — how many bytes one pointer addresses, for this call.
 *
 * `params` is the caller's parameter block, already copied in, and at least
 * `params_size` bytes. Returns a length, or -EINVAL when the count cannot be
 * read or is over the bound -- which is the backend's answer too, so the call
 * is refused in one place rather than half-served from here.
 */
static inline long nvgpu_rmctrl_len(const struct nvgpu_rmctrl_ptr *p,
				    const void *params, u32 params_size)
{
	u64 count = 0, bytes;

	switch (p->count_kind) {
	case NVGPU_RMCTRL_FIXED:
		count = p->fixed;
		break;
	case NVGPU_RMCTRL_FIELD:
	case NVGPU_RMCTRL_SQUARED:
		if (p->count_offset + p->count_width > params_size)
			return -EINVAL;
		switch (p->count_width) {
		case 1:
			count = *((const u8 *)params + p->count_offset);
			break;
		case 2: {
			u16 v;

			memcpy(&v, (const u8 *)params + p->count_offset,
			       sizeof(v));
			count = le16_to_cpu((__force __le16)v);
			break;
		}
		case 4: {
			u32 v;

			memcpy(&v, (const u8 *)params + p->count_offset,
			       sizeof(v));
			count = le32_to_cpu((__force __le32)v);
			break;
		}
		case 8: {
			u64 v;

			memcpy(&v, (const u8 *)params + p->count_offset,
			       sizeof(v));
			count = le64_to_cpu((__force __le64)v);
			break;
		}
		default:
			return -EINVAL;
		}
		if (p->count_kind == NVGPU_RMCTRL_SQUARED) {
			if (count > U32_MAX)
				return -EINVAL;
			count *= count;
		}
		break;
	default:
		return -EINVAL;
	}

	bytes = count * p->elem_size;
	if (p->elem_size && count > div64_u64(NVGPU_RMCTRL_MAX_BYTES, p->elem_size))
		return -EINVAL;
	if (bytes > NVGPU_RMCTRL_MAX_BYTES)
		return -EINVAL;
	return (long)bytes;
}

#endif /* NVGPU_RMCTRL_H */
